SELECT 
    z.ZPERIOD,
    z.ZAMNT,
    z1.ID ACCID,
    isnull(z2.ID, 0) ZSK00,
    isnull(z3.ID, 0) ZSK01,
    isnull(z4.ID, 0) ZSK02,
    isnull(z5.ID, 0) ZSK03,
    isnull(z6.ID, 0) ZSK10,
    isnull(z7.ID, 0) ZSK11,
    isnull(z8.ID, 0) ZSK12,
    isnull(z9.ID, 0) ZSK13,
    isnull(z10.ID, 0) ZSK20
INTO ZFACT
FROM #ZFACT z
LEFT JOIN ZSUBKONTO z1 ON z1.Z_TYPE = z.ZBDACCT AND z1.Z_REF = z.ZBDACCR
LEFT JOIN ZSUBKONTO z2 ON z2.Z_TYPE = z.ZSK00T    AND z2.Z_REF = z.ZSK00R
LEFT JOIN ZSUBKONTO z3 ON z3.Z_TYPE = z.ZSK01T    AND z3.Z_REF = z.ZSK01R
LEFT JOIN ZSUBKONTO z4 ON z4.Z_TYPE = z.ZSK02T    AND z4.Z_REF = z.ZSK02R
LEFT JOIN ZSUBKONTO z5 ON z5.Z_TYPE = z.ZSK03T    AND z5.Z_REF = z.ZSK03R
LEFT JOIN ZSUBKONTO z6 ON z6.Z_TYPE = z.ZSK10T    AND z6.Z_REF = z.ZSK10R
LEFT JOIN ZSUBKONTO z7 ON z7.Z_TYPE = z.ZSK11T    AND z7.Z_REF = z.ZSK11R
LEFT JOIN ZSUBKONTO z8 ON z8.Z_TYPE = z.ZSK12T    AND z8.Z_REF = z.ZSK12R
LEFT JOIN ZSUBKONTO z9 ON z9.Z_TYPE = z.ZSK13T    AND z9.Z_REF = z.ZSK13R
LEFT JOIN ZSUBKONTO z10 ON z10.Z_TYPE = z.ZSK20T  AND z10.Z_REF = z.ZSK20R;
