CREATE TABLE ZLSSTORE
(
    ZKEY0 BIGINT NOT NULL,
    --ZSTORE_LEGALENTITY_STORE BIGINT NULL,
    ZSTRETYPE BIGINT NULL,
    --ZPRICELISTSTORE_DATARETAILCALCPRICELISTTYPE_STORE BIGINT NULL,
    --ZPRICELISTSTORE_RETAILCALCPRICELISTTYPE_STORE BIGINT NULL,
    --ZPRICELISTSTORE_DATARETAILPRICELISTTYPE_STORE BIGINT NULL,
    ZPRICELISTSTORE_RETAILPRICELISTTYPE_STORE BIGINT NULL,
    ZSTORE_ID_STORE NVARCHAR(100) NULL,
    ZSTORE_BANKACCOUNT_STORE BIGINT NULL,
    ZSTORE_CHAIRMAN_STORE BIGINT NULL,
    ZSTORE_ADDRESS_STORE NVARCHAR(150) NULL,
    ZSTORE_NAME_STORE NVARCHAR(100) NULL,
    ZRANGE_USERANGE_STORE INT NULL,
    ZSALE_ISCORPORATE_STORE INT NULL,
    ZSTORE_REGION_STORE BIGINT NULL,
    ZSTORE_EMAIL_STORE NVARCHAR(300) NULL,
    ZSALE_ISINTERNET_STORE INT NULL,
    ZSTORE_LATITUDE_STORE DECIMAL(11,6) NULL,
    ZSTORE_OPENDATE_STORE DATE NULL,
    ZSTORE_ORDERNUMBER_STORE INT NULL,
    ZSTORE_LONGITUDE_STORE DECIMAL(11,6) NULL,
    ZSTORE_CLOSETIME_STORE TIME(7) NULL,
    ZCASHREGISTER_COUNTDATACASHREGISTER_STORE INT NULL,
    ZSTORE_INACTIVE_STORE INT NULL,
    ZSTORE_PHONE_STORE NVARCHAR(100) NULL,
    ZSYSTEM__CLASS_STORE_STORE BIGINT NULL,
    ZSTORE_OPENTIME_STORE TIME(7) NULL,
    ZSTORE_CLOSEDATE_STORE DATE NULL,
    ZPRICELIMIT_PRICELIMITPRICELISTTYPE_STORE BIGINT NULL,
    ZSTORE_TOTALSQUARE_STORE DECIMAL(10,2) NULL,
    ZSTORE_RENTSQUARE_STORE DECIMAL(10,2) NULL,
    ZSTORE_CITY_STORE BIGINT NULL,
    ZSTORE_MANAGER_STORE BIGINT NULL,
    ZSTORE_RENT_STORE INT NULL,
    ZIMPORTGESTORI_EXTID_STORE NVARCHAR(100) NULL,
    ZPURCHASE_SELECTCOUNTRANGE_STORE INT NULL,
    ZSTORE_REGIONGROUP_STORE BIGINT NULL,
    ZSTORE_WAREHOUSE_STORE BIGINT NULL,
    ZPRICELIST_WHOLESALEMARKUPPRICELISTTYPE_STORE BIGINT NULL,
    ZSTORE_TEMPORARYCLOSED_STORE INT NULL,
    ZSTORE_ALLDAY_STORE INT NULL,
    ZABMSHELF_STATUSABM_STORE BIGINT NULL,
    ZMARKETING_HASAUDIO_STORE INT NULL,
    ZSTORE_DAYSORDERBEFOREOPEN_STORE INT NULL,
    Z_DELETED_SCMMASTERDATA_ACTIVEREPLENISHMENT_STORE INT NULL,
    ZSTORE_DAYSORDERBEFORECLOSE_STORE INT NULL,
    Z_DELETED_SCMMASTERDATA_PRIORITY_STORE INT NULL,
    Z_DELETED_SCMMASTERDATA_ANALOGSTORE_STORE BIGINT NULL,
    Z_DELETED_SCMMASTERDATA_NEEDUPDATE_STORE INT NULL,
    Z_DELETED_SCM_PRIORITY_STORE INT NULL,
    Z_DELETED_SCM_ANALOGSTORE_STORE BIGINT NULL,
    Z_DELETED_SCM_ACTIVEREPLENISHMENT_STORE INT NULL,
    Z_DELETED_SCM_NEEDUPDATE_STORE INT NULL,
    ZRANGE_DEFAULTRANGELEVEL_STORE BIGINT NULL,
    ZSALE_STORETELEGRAMCHATID_STORE NVARCHAR(MAX) NULL,
    ZSTORE_ACCOUNTANT_STORE BIGINT NULL,
    ZRANGE_RANGECHAINSTORIES_STORE BIGINT NULL,
    ZRANGE_BASERANGELEVEL_STORE BIGINT NULL,
    ZSTORE_REGIONAL_STORE INT NULL,
    ZSTORE_DISTRICT_STORE INT NULL,
    CONSTRAINT STORE_STORE_PKEY PRIMARY KEY CLUSTERED (ZKEY0 ASC)
);
GO

-- NON-CLUSTERED INDEXES

CREATE NONCLUSTERED INDEX STORE_ID_STORE_KEY0_IDX_STORE_STORE
    ON DBO.STORE_STORE (ZSTORE_ID_STORE ASC, ZKEY0 ASC);
GO

CREATE NONCLUSTERED INDEX STORE_LEGALENTITY_STORE_IDX_STORE_STORE
    ON DBO.STORE_STORE (ZSTORE_LEGALENTITY_STORE ASC);
GO

CREATE NONCLUSTERED INDEX STORE_NAME_STORE_KEY0_IDX_STORE_STORE
    ON DBO.STORE_STORE (ZSTORE_NAME_STORE ASC, ZKEY0 ASC);
GO

CREATE NONCLUSTERED INDEX STORE_STORETYPE_STORE_IDX_STORE_STORE
    ON DBO.STORE_STORE (ZSTORE_STORETYPE_STORE ASC);
GO

CREATE NONCLUSTERED INDEX STORE_WAREHOUSE_STORE_IDX_STORE_STORE
    ON DBO.STORE_STORE (ZSTORE_WAREHOUSE_STORE ASC);