CREATE TABLE DBO.STORE_DEPARTMENTSTORE
(
    ZKEY0 BIGINT NOT NULL,
    ZSTORE_STORE_DEPARTMENTSTORE BIGINT NULL,
    ZSTORE_LEGALENTITY_DEPARTMENTSTORE BIGINT NULL,
    ZSTORE_DATASTOCKGROUP_DEPARTMENTSTORE BIGINT NULL,
    ZSTORE_INACTIVE_DEPARTMENTSTORE INT NULL,
    ZPRICING_COSTLEDGER_DEPARTMENTSTORE INT NULL,
    ZSTORE_EXPLICITBATCHLEDGER_DEPARTMENTSTORE INT NULL,
    ZPRICELISTSTORE_RETAILCALCPRICELISTTYPE_DEPARTMENTSTORE BIGINT NULL,
    ZPRICELISTSTORE_RETAILPRICELISTTYPE_DEPARTMENTSTORE BIGINT NULL,
    ZSTORE_DATAPRICEBATCHLEDGER_DEPARTMENTSTORE INT NULL,
    ZCASHREGISTER_STARTDATEGROUPCASHREGISTER_DEPARTMENTSTORE DATE NULL,
    ZPRICEROUNDSTORE_DATAROUNDCONDITION_DEPARTMENTSTORE BIGINT NULL,
    ZPRICEROUNDSTORE_ROUNDCONDITIONCOUNTRY_DEPARTMENTSTORE BIGINT NULL,
    ZPRICEROUNDSTORE_ROUNDCONDITION_DEPARTMENTSTORE BIGINT NULL,
    ZPRICEROUNDSTORE_DATADISCOUNROUNDCONDITION_DEPARTMENTSTORE BIGINT NULL, -- Note: spelling aligned to source column
    ZPRICEROUNDSTORE_ROUNDDISCOUNTCONDITION_DEPARTMENTSTORE BIGINT NULL,
    ZSTORE_ID_DEPARTMENTSTORE NVARCHAR(100) NULL,
    ZSTORE_CASHACCOUNT_DEPARTMENTSTORE BIGINT NULL,
    ZSTORE_AUTOCLOSEORDERS_DEPARTMENTSTORE INT NULL,
    ZSTORE_QUANTITYDAYSCLOSE_DEPARTMENTSTORE INT NULL,
    ZPRICING_PRICINGCOMMITTEE_DEPARTMENTSTORE BIGINT NULL,
    ZSTORE_NAME_DEPARTMENTSTORE NVARCHAR(150) NULL,
    ZPRICING_DATEBANRETAILPRICE_DEPARTMENTSTORE DATE NULL,
    ZSTORE_FULLNAME_DEPARTMENTSTORE NVARCHAR(150) NULL,
    ZRANGE_USERANGE_DEPARTMENTSTORE INT NULL,
    ZSTORE_STORETYPE_DEPARTMENTSTORE BIGINT NULL,
    ZSTORE_CHAINSTORES_DEPARTMENTSTORE BIGINT NULL,
    ZSYSTEM__CLASS_STORE_DEPARTMENTSTORE BIGINT NULL,
    ZSTORE_DATAPHONE_DEPARTMENTSTORE NVARCHAR(100) NULL,
    ZEDI_SKIPEDI_DEPARTMENTSTORE INT NULL,
    Z_DELETED_EDI_PASSWORDEDSSERVICE_DEPARTMENTSTORE NVARCHAR(100) NULL,
    Z_DELETED_EDI_ALIASEDSSERVICE_DEPARTMENTSTORE NVARCHAR(100) NULL,
    Z_DELETED_EDI_HOSTEDSSERVICETOPBY_DEPARTMENTSTORE NVARCHAR(100) NULL,
    Z_DELETED_EDI_PORTEDSSERVICETOPBY_DEPARTMENTSTORE INT NULL,
    ZPURCHASE_SKIPCOUNTRANGE_DEPARTMENTSTORE INT NULL,
    ZINTEGRATION_CODECAPITAL_DEPARTMENTSTORE VARCHAR(2) NULL,
    ZSTORE_STOREGROUP_DEPARTMENTSTORE BIGINT NULL,
    Z_DELETED_EDI_HOSTEDSSERVICEEDN_DEPARTMENTSTORE NVARCHAR(100) NULL,
    Z_DELETED_EDI_PORTEDSSERVICEEDN_DEPARTMENTSTORE INT NULL,
    ZPURCHASE_AUTODERIVELASTCERTIFICATE_DEPARTMENTSTORE INT NULL,
    ZLABEL_EXTRAPRINTER_DEPARTMENTSTORE BIGINT NULL,
    ZINTEGRATION_CODETTL_DEPARTMENTSTORE INT NULL,
    ZPRICELIMIT_PRICELIMITPRICELISTTYPE_DEPARTMENTSTORE BIGINT NULL,
    ZPRICELIMIT_BASEPRICELIMITPRICELISTTYPE_DEPARTMENTSTORE BIGINT NULL,
    ZPURCHASE_SELECTEDCOUNTRANGE_DEPARTMENTSTORE INT NULL,
    ZITEM_IDVITALUR_DEPARTMENTSTORE NVARCHAR(MAX) NULL,
    ZRESTFRONT_PASSWORDRESTFRONT_DEPARTMENTSTORE NVARCHAR(255) NULL,
    ZRESTFRONT_USERNAMERESTFRONT_DEPARTMENTSTORE NVARCHAR(255) NULL,
    ZRESTFRONT_URLAPI_DEPARTMENTSTORE NVARCHAR(255) NULL,
    ZRESTFRONT_IDMENURESTFRONT_DEPARTMENTSTORE INT NULL,
    ZRESTFRONT_SYSTEMKEY_DEPARTMENTSTORE INT NULL,
    ZRESTFRONT_LASTEXPORTEDALL_DEPARTMENTSTORE DATETIME2 NULL,
    ZSCALES_MAXMINALLPLUNUMBER_DEPARTMENTSTORE INT NULL,
    ZSCALES_MINMAXALLPLUNUMBER_DEPARTMENTSTORE INT NULL,
    ZSCALES_MAXMAXALLPLUNUMBER_DEPARTMENTSTORE INT NULL,
    ZSKULEDGERSANTA_CALCULATESTORAGEPERIOD_DEPARTMENTSTORE INT NULL,
    ZZONESANTA_USECUSTOMERZONE_DEPARTMENTSTORE INT NULL,
    ZBIN_USEBINS_DEPARTMENTSTORE INT NULL,
    ZSTORE_RETAILDEPARTMENT_DEPARTMENTSTORE INT NULL,
    Z_DELETED_SCM_ACTIVEREPLENISHMENT_DEPARTMENTSTORE INT NULL,
    ZSTORE_USEPALLET_DEPARTMENTSTORE INT NULL,
    ZPURCHASE_AUTODERIVELASTCERTIFICATECOMPLIANCE_DEPARTMENTSTORE INT NULL,
    ZCONSIGNMENT_SHIPMENTBASE_DEPARTMENTSTORE NVARCHAR(100) NULL,
    ZSALE_ISCATERING_DEPARTMENTSTORE INT NULL,
    Z_DELETED_YANDEXEDA_ISINTERNETSTOCK_DEPARTMENTSTORE INT NULL,
    ZSALE_ISINTERNETSTOCK_DEPARTMENTSTORE INT NULL,
    ZSALE_BLOCKTIMEFROM_DEPARTMENTSTORE TIME(7) NULL,
    ZSALE_BLOCKTIMETO_DEPARTMENTSTORE TIME(7) NULL,
    ZPURCHASE_SCHEDULEORDER_DEPARTMENTSTORE INT NULL,
    ZCONSIGNMENT_DECISIONMAKEROVERLOAD_DEPARTMENTSTORE NVARCHAR(150) NULL,
    ZCONSIGNMENT_USEOVERLOADINFO_DEPARTMENTSTORE INT NULL,
    ZSPUTNIK_AUTOORDERSPUTNIK_DEPARTMENTSTORE INT NULL,
    CONSTRAINT STORE_DEPARTMENTSTORE_PKEY PRIMARY KEY CLUSTERED (ZKEY0 ASC)
);
GO

-- NON-CLUSTERED INDEXES

CREATE NONCLUSTERED INDEX STORE_CHAINSTORES_DEPARTMENTSTORE_IDX_STORE_DEPARTMENTSTORE
    ON DBO.STORE_DEPARTMENTSTORE (ZSTORE_CHAINSTORES_DEPARTMENTSTORE ASC);
GO

CREATE NONCLUSTERED INDEX STORE_FULLNAME_DEPARTMENTSTORE_KEY0_IDX_STORE_DEPARTMENTSTORE
    ON DBO.STORE_DEPARTMENTSTORE (ZSTORE_FULLNAME_DEPARTMENTSTORE ASC, ZKEY0 ASC);
GO

CREATE NONCLUSTERED INDEX STORE_ID_DEPARTMENTSTORE_KEY0_IDX_STORE_DEPARTMENTSTORE
    ON DBO.STORE_DEPARTMENTSTORE (ZSTORE_ID_DEPARTMENTSTORE ASC, ZKEY0 ASC);
GO

CREATE NONCLUSTERED INDEX STORE_LEGALENTITY_DEPARTMENTSTORE_IDX_STORE_DEPARTMENTSTORE
    ON DBO.STORE_DEPARTMENTSTORE (ZSTORE_LEGALENTITY_DEPARTMENTSTORE ASC);
GO

CREATE NONCLUSTERED INDEX STORE_NAME_DEPARTMENTSTORE_KEY0_IDX_STORE_DEPARTMENTSTORE
    ON DBO.STORE_DEPARTMENTSTORE (ZSTORE_NAME_DEPARTMENTSTORE ASC, ZKEY0 ASC);
GO

CREATE NONCLUSTERED INDEX STORE_STORE_DEPARTMENTSTORE_IDX_STORE_DEPARTMENTSTORE
    ON DBO.STORE_DEPARTMENTSTORE (ZSTORE_STORE_DEPARTMENTSTORE ASC);
GO

CREATE NONCLUSTERED INDEX STORE_STOREGROUP_DEPARTMENTSTORE_IDX_STORE_DEPARTMENTSTORE
    ON DBO.STORE_DEPARTMENTSTORE (ZSTORE_STOREGROUP_DEPARTMENTSTORE ASC);
GO

CREATE NONCLUSTERED INDEX STORE_STORETYPE_DEPARTMENTSTORE_IDX_STORE_DEPARTMENTSTORE
    ON DBO.STORE_DEPARTMENTSTORE (ZSTORE_STORETYPE_DEPARTMENTSTORE ASC);