IF OBJECT_ID(N'DBO.STOCK_STOCK', N'U') IS NOT NULL
    DROP TABLE DBO.STOCK_STOCK;
GO

CREATE TABLE DBO.STOCK_STOCK
(
    ZKEY0 BIGINT NOT NULL,
    ZSTOCK_LEGALENTITY_STOCK BIGINT NULL,
    ZSTOCK_ISCOMPANY_STOCK INT NULL,
    ZSTOCK_STOCKGROUP_STOCK BIGINT NULL,
    ZSTOCK_COUNTRY_STOCK BIGINT NULL,
    ZSTOCK_DEFAULT_STOCK INT NULL,
    ZSTOCK_CURRENCY_STOCK BIGINT NULL,
    ZSTOCK_EXPLICITBATCHLEDGER_STOCK INT NULL,
    ZSTOCK_PRICEBATCHLEDGER_STOCK INT NULL,
    ZSTOCK_ID_STOCK NVARCHAR(100) NULL,
    ZREPRICINGCOMMITTEE_REPRICINGCOMMITTEE_STOCK BIGINT NULL,
    ZSTOCKDOCUMENT_DOCUMENTSCLOSEDDATE_STOCK DATE NULL,
    ZPURCHASE_DATAAUTOCLOSEORDERS_STOCK INT NULL,
    ZSTOCK_AUTOCLOSEORDERS_STOCK INT NULL,
    ZPURCHASE_DATAQUANTITYDAYSCLOSEORDERS_STOCK INT NULL,
    ZSTOCK_QUANTITYDAYSCLOSEORDERS_STOCK INT NULL,
    ZPURCHASERETURN_DATAAUTOCLOSEORDERS_STOCK INT NULL,
    ZPURCHASERETURN_DATAQUANTITYDAYSCLOSEORDERS_STOCK INT NULL,
    ZSALE_DATAAUTOCLOSEORDERS_STOCK INT NULL,
    ZSALE_DATAQUANTITYDAYSCLOSEORDERS_STOCK INT NULL,
    ZSALERETURN_DATAAUTOCLOSEORDERS_STOCK INT NULL,
    ZSALERETURN_DATAQUANTITYDAYSCLOSEORDERS_STOCK INT NULL,
    ZORDERLEDGER_BANNEGATIVESKU_STOCK INT NULL,
    ZORDERLEDGER_BANNEGATIVEBATCH_STOCK INT NULL,
    ZWRITEOFF_WRITEOFFCOMMITTEE_STOCK BIGINT NULL,
    ZSTOCK_NAME_STOCK NVARCHAR(150) NULL,
    ZPURCHASE_DATEBANVALUEVAT_STOCK DATE NULL,
    ZPURCHASE_DATEBANBARCODE_STOCK DATE NULL,
    ZPURCHASERETURN_DATABASEINVOICEDETAIL_STOCK DATE NULL,
    ZCONSIGNMENT_WAYOFUNLOADING_STOCK BIGINT NULL,
    ZSTOCK_ADDRESS_STOCK NVARCHAR(150) NULL,
    ZSTOCK_FULLNAME_STOCK NVARCHAR(150) NULL,
    ZCONSIGNMENT_LOADINGEXECUTER_STOCK BIGINT NULL,
    ZCONSIGNMENT_ADDRESSCONSIGMENTLEGALENTITY_STOCK NVARCHAR(150) NULL,
    ZCONSIGNMENT_CODELOADING_STOCK CHAR(3) NULL,
    ZEDI_DATAGLN_STOCK NVARCHAR(13) NULL,
    ZREPRICINGCOMMITTEE_NUMBERDISPOSAL_STOCK NVARCHAR(50) NULL,
    ZCONSIGNMENT_ISSUANCEALLOWED_STOCK BIGINT NULL,
    ZCONSIGNMENT_UNLOADINGEXECUTER_STOCK BIGINT NULL,
    ZSTOCK_REGION_STOCK BIGINT NULL,
    ZSTOCK_EMAIL_STOCK NVARCHAR(300) NULL,
    ZCONSIGNMENT_ISSUANCEEXECUTED_STOCK BIGINT NULL,
    ZCONSIGNMENT_UNPLEGALENTITY_STOCK NVARCHAR(50) NULL,
    ZCONSIGNMENT_WAYOFLOADING_STOCK BIGINT NULL,
    ZSTOCK_LANGUAGE_STOCK BIGINT NULL,
    ZCONSIGNMENT_NAMECONSIGMENTLEGALENTITY_STOCK NVARCHAR(200) NULL,
    ZSTOCK_PHONE_STOCK NVARCHAR(100) NULL,
    ZSTOCK_ACTIVE_STOCK INT NULL,
    ZSALEREPORTS_INSALEREPORT_STOCK INT NULL,
    ZIMPORTGESTORI_EXTID_STOCK NVARCHAR(100) NULL,
    ZSTOCK_DATEACCOUNTDELTA_STOCK DATE NULL,
    ZLEGALENTITY_USESECONDPRICE_STOCK INT NULL,
    ZCASHREGISTER_STARTDATEGROUPCASHREGISTER_STOCK DATE NULL,
    ZMARKETING_COUNTSTOCKGROUPS_STOCK INT NULL,
    ZPURCHASE_CUSTODYWAREHOUSE_STOCK BIGINT NULL,
    Z_DELETED_BIN_GROUPTYPE_STOCK BIGINT NULL,
    Z_DELETED_INTEGRATION_STATUS_STOCK INT NULL,
    ZPURCHASE_CUSTODYCONTRACTDATE_STOCK DATE NULL,
    ZPURCHASE_CUSTODYCONTRACT_STOCK NVARCHAR(100) NULL,
    Z_DELETED_INTEGRATION_STATUSNOTE_STOCK NVARCHAR(500) NULL,
    ZORDERLEDGERSANTA_ALLOWNEGATIVESHIPMENTSKU_STOCK INT NULL,
    ZORDERLEDGERSANTA_ALLOWNEGATIVESHIPMENTBATCH_STOCK INT NULL,
    ZPURCHASERETURN_DATAPURCHASERETURNEDI_STOCK INT NULL,
    ZPURCHASE_ALLOWNULLTERMINALINVOICE_STOCK INT NULL,
    Z_DELETED_PURCHASE_ALLOWNULLORDERIDETAILINVOICEDETAIL_STOCK INT NULL,
    Z_DELETED_PURCHASE_ALLOWNULLORDERINVOICE_STOCK INT NULL,
    ZPURCHASE_ALLOWNULLORDERIDETAILPURCHASEINVOICEDETAIL_STOCK INT NULL,
    ZPURCHASE_ALLOWNULLORDERPURCHASEINVOICE_STOCK INT NULL,
    Z_DELETED_PURCHASERETURNINVOICESANTA_ALLOWNULLORDERIDETAILPURCHA INT NULL,
    Z_DELETED_PURCHASERETURNINVOICESANTA_ALLOWNULLORDERPURCHASERETUR INT NULL,
    ZNATURALLOSS_INCUSTODY_STOCK INT NULL,
    ZEDI_PASSWORDEDSSERVICE_STOCK NVARCHAR(100) NULL,
    ZEDI_ALIASEDSSERVICE_STOCK NVARCHAR(150) NULL,
    ZPURCHASE_AUTODERIVELASTCERTIFICATE_STOCK INT NULL,
    ZSTOCKREPORTS_DATAINPRICEMONITORING_STOCK INT NULL,
    ZREMINDERSANTA_CHECKLABELSLOGIN_STOCK INT NULL,
    ZNATURALLOSSSTOCK_DATANATURALLOSSSTOCKTYPE_STOCK BIGINT NULL,
    ZSALE_DATASALEEDI_STOCK INT NULL,
    Z_DELETED_EDI_EDSSERVICEEDN_STOCK BIGINT NULL,
    ZEDI_EDSSERVICETOPBY_STOCK BIGINT NULL,
    ZEDN_EDSSERVICE_STOCK BIGINT NULL,
    ZEDN_PASSWORDEDSSERVICE_STOCK NVARCHAR(100) NULL,
    ZEDN_ALIASEDSSERVICE_STOCK NVARCHAR(150) NULL,
    ZPURCHASERETURN_ALLOWNULLORDERIDETAILPURCHASERETURNINVOICEDETAIL INT NULL,
    ZPURCHASERETURN_ALLOWNULLORDERPURCHASERETURNINVOICE_STOCK INT NULL,
    ZISWMSINTEGRATION_EXPORTERROR_STOCK INT NULL,
    ZISWMSINTEGRATION_EXPORTERRORLOG_STOCK NVARCHAR(MAX) NULL,
    ZSTOCK_EXTRASTOCKGROUP_STOCK BIGINT NULL,
    ZSKULEDGERSANTA_CALCULATESTORAGEPERIOD_STOCK INT NULL,
    ZPURCHASE_SHOWEXPIRYDATE_STOCK INT NULL,
    ZBIN_USEBINS_STOCK INT NULL,
    ZBIN_STOCKBINGROUP_STOCK BIGINT NULL,
    Z_DELETED_SCMMASTERDATA_NEEDUPDATE_STOCK INT NULL,
    Z_DELETED_SCM_NEEDUPDATE_STOCK INT NULL,
    Z_DELETED_SCM_IDSCM_STOCK NVARCHAR(10) NULL,
    ZEDI_EDSFROM_STOCK DATETIME2 NULL,
    ZEDI_EDSTO_STOCK DATETIME2 NULL,
    ZEDI_EDSDAYS_STOCK INT NULL,
    ZPURCHASE_AUTODERIVELASTCERTIFICATECOMPLIANCE_STOCK INT NULL,
    ZEDI_SKIPEDI_STOCK INT NULL,
    ZINVOICE_ISALCOHOLFOREIGN_STOCK INT NULL,
    ZMACHINERY_LOTUPLOAD_STOCK INT NULL,
    ZEDI_USEMAINGLN_STOCK INT NULL,
    ZRANGE_USERANGE_STOCK INT NULL,
    ZINTEGRATION_ISVPI_STOCK INT NULL,
    ZPURCHASE_SKIPCREATESALEORDERLEDGER_STOCK INT NULL,
    ZINTEGRATION_CODETTL_STOCK INT NULL,
    ZPURCHASE_CUSTODIANWAREHOUSE_STOCK BIGINT NULL,
    ZPURCHASE_DATAPRIORITYINTRADEMAND_STOCK INT NULL,
    ZPURCHASE_CREATESALEORDERLEDGERCHECKED_STOCK INT NULL,
    ZSTOCK_DISTRICT_STOCK BIGINT NULL,
    ZSTOCK_CITY_STOCK BIGINT NULL,
    ZPURCHASE_SCHEDULEORDER_STOCK INT NULL,
    ZSPUTNIK_IDSTOCK_STOCK BIGINT NULL,
    ZASSORTMENTREPORT_COMPANYSUPPLIERWAREHOUSE_STOCK INT NULL,
    ZPURCHASE_DATADENYDEVIATIONAUTO_STOCK INT NULL,
    ZPURCHASE_DENYDEVIATIONAUTO_STOCK INT NULL,
    ZTERMINALHANDLER_TRUSTACCEPT_STOCK INT NULL,
    ZTERMINALHANDLER_TRUSTACCEPTPERCENT_STOCK DECIMAL(6,2) NULL,
    ZSALE_LASTCONSIGNMENTPAYER_STOCK BIGINT NULL,
    ZSALE_LASTCONSIGNMENTTRUCK_STOCK BIGINT NULL,
    ZSALE_LASTCONSIGNMENTDRIVER_STOCK BIGINT NULL,
    ZSALE_LASTCONSIGNMENTWAYBILL_STOCK NVARCHAR(20) NULL,
    ZSALE_LASTCONSIGNMENTISSUANCEEXECUTED_STOCK BIGINT NULL,
    ZSALE_LASTCONSIGNMENTFORWARDER_STOCK BIGINT NULL,
    CONSTRAINT STOCK_STOCK_PKEY PRIMARY KEY CLUSTERED (ZKEY0 ASC)
);
GO

-- NON-CLUSTERED INDEXES

CREATE NONCLUSTERED INDEX BIN_STOCKBINGROUP_STOCK_IDX_STOCK_STOCK
    ON DBO.STOCK_STOCK (ZBIN_STOCKBINGROUP_STOCK ASC);
GO

CREATE NONCLUSTERED INDEX SPUTNIK_IDSTOCK_STOCK_KEY0_IDX_STOCK_STOCK
    ON DBO.STOCK_STOCK (ZSPUTNIK_IDSTOCK_STOCK ASC, ZKEY0 ASC);
GO

CREATE NONCLUSTERED INDEX STOCK_FULLNAME_STOCK_IDX_STOCK_STOCK
    ON DBO.STOCK_STOCK (ZSTOCK_FULLNAME_STOCK ASC);
GO

CREATE NONCLUSTERED INDEX STOCK_ID_STOCK_KEY0_IDX_STOCK_STOCK
    ON DBO.STOCK_STOCK (ZSTOCK_ID_STOCK ASC, ZKEY0 ASC);
GO

CREATE NONCLUSTERED INDEX STOCK_LEGALENTITY_STOCK_IDX_STOCK_STOCK
    ON DBO.STOCK_STOCK (ZSTOCK_LEGALENTITY_STOCK ASC);
GO

CREATE NONCLUSTERED INDEX STOCK_NAME_STOCK_IDX_STOCK_STOCK
    ON DBO.STOCK_STOCK (ZSTOCK_NAME_STOCK ASC);
GO

CREATE NONCLUSTERED INDEX STOCK_PHONE_STOCK_KEY0_IDX_STOCK_STOCK
    ON DBO.STOCK_STOCK (ZSTOCK_PHONE_STOCK ASC, ZKEY0 ASC);
GO

CREATE NONCLUSTERED INDEX STOCK_STOCKGROUP_STOCK_IDX_STOCK_STOCK
    ON DBO.STOCK_STOCK (ZSTOCK_STOCKGROUP_STOCK ASC);
GO